"""Init

Revision ID: c8d97932e11f
Revises: 73ad12e770d0
Create Date: 2024-06-16 14:11:43.819243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d97932e11f'
down_revision: Union[str, None] = '73ad12e770d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('date_of', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'date_of')
    # ### end Alembic commands ###
